### ISSUE TITLE
Test wifi dropout

### ISSUE THREAD

**Issue by viomonger** [MagicSmokeFireworks/magic-smoke-firmware#1]

**Comment by viomonger** [comment]
boards do not reconnect

**Comment by viomonger** [comment]
Fixed in version of firmware that hasn't been uploaded to github yet. Close this when it does, and after more testing.

**Comment by DaedalusSC** [comment]
Then we should upload that, so we can test :)

**Comment by viomonger** [comment]
ok fine, test away!
